# SCD configs
stage:
    global:
        SKIP_HTML_MINIFICATION: true
        SCD_ON_DEMAND: true
    build:
        VERBOSE_COMMANDS: "-vv"
        SCD_THREADS: 4
        SCD_STRATEGY: "standard"
        SCD_MAX_EXECUTION_TIME: 900
        SCD_MATRIX:
            "Magento/backend":
                language:
                    - en_US
                    - pt_BR
            "Webjump/theme-frontend-translate":
                "language":
                    - pt_BR
            "Webjump/theme-frontend-carbono":
                "language":
                    - pt_BR
            "Webjump/theme-frontend-broto":
                "language":
                    - pt_BR
    deploy:
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 10000
            consumers: []
        CLEAN_STATIC_FILES: false
        SCD_MATRIX:
            "Magento/backend": []
            "Magento/luma": []
            "Magento/blank": []
#        SEARCH_CONFIGURATION:
#            engine: elasticsearch6
#            _merge: true
        MYSQL_USE_SLAVE_CONNECTION: true
        REDIS_USE_SLAVE_CONNECTION: true
        ENABLE_GOOGLE_ANALYTICS: true
