# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.2
    disk: 2048
    configuration:
        schemas:
            - main
        endpoints:
            admin:
                default_schema: main
                privileges:
                    main: admin
            mysql:
                default_schema: main
                privileges:
                    main: admin
            mbi:
                default_schema: main
                privileges:
                    main: ro

redis:
    type: redis:5.0

elasticsearch:
    type: elasticsearch:6.5
    disk: 1024

rabbitmq:
    type: rabbitmq:3.5
    disk: 1024
